name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7  # Specify the version of pnpm you want to use
      - name: Install Dependencies
        run: pnpm install  # Use pnpm to install dependencies
      - name: Lint
        run: pnpm run lint  # Run lint using pnpm

  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7  # Specify the version of pnpm you want to use
      - name: Install Dependencies
        run: pnpm install  # Use pnpm to install dependencies
      - name: Run Tests
        run: pnpm test  # Run tests using pnpm

